### ISSUE TITLE
vytvoření mapy

### ISSUE THREAD

**Issue by jachym** [raugustyn/TB04CUZK001_Cepicky#4]
vytvoření  mapy s prázdnou mapou v OL3

- jako overlay rastrový obrázek, viz issue #8
- podkladová mapa zabaged z wms  - měřítko 1:10  1:25
- overlay [vektory] (http://www.vugtk.cz/euradin/TB04CUZK001/OLv3.10.1/OLv3.10.1/examples/data/geojson/TestData01.geojson)  - viz issue #6

to celé jako github.io projekt

**Comment by jachym** [comment]
ideálně do **10.12.2015**

**Comment by raugustyn** [comment]
@jachym napsal: asi takhle nějek?

http://raugustyn.github.io/TB04CUZK001_Cepicky/deploy/index.html

**Comment by raugustyn** [comment]
Jo, přibližně tak jako maketa.

1. Chybí tam ten json co jsem poslal v příkladu z #4, tj. http://www.vugtk.cz/euradin/TB04CUZK001/OLv3.10.1/OLv3.10.1/examples/data/geojson/TestData01.geojson
2. Mapa z ČÚZK by měla být ta z WMTS, tahle se při zvětšení na celou obrazovku nezobrazí bo ČÚZK je sto let za opicema a stále nechápe že lidi co makaj s mapama maj 4K monitory, viz #4.
3. Ta minimalizace pomocí gulp je až fáze za tím, ono to bude nějakou formou zakompoované na tom portálu.

**Comment by raugustyn** [comment]
To oživení Křováka pomocí proj4 je tam taky navíc, ale dík za příklad. Obešli bysme se s místní sítí.

**Comment by raugustyn** [comment]
Oky, připomínky jsem rozepsal jako samostatné Issues:
#6, #9
